# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x07\x64\x65\x66\x61ult\"\x17\n\x08Response\x12\x0b\n\x03res\x18\x01 \x01(\t\"\x15\n\x05\x45vent\x12\x0c\n\x04text\x18\x01 \x01(\t2>\n\x0cNotification\x12.\n\tsendEvent\x12\x0e.default.Event\x1a\x11.default.Responseb\x06proto3')



_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_EVENT = DESCRIPTOR.message_types_by_name['Event']
Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:default.Response)
  })
_sym_db.RegisterMessage(Response)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:default.Event)
  })
_sym_db.RegisterMessage(Event)

_NOTIFICATION = DESCRIPTOR.services_by_name['Notification']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=31
  _RESPONSE._serialized_end=54
  _EVENT._serialized_start=56
  _EVENT._serialized_end=77
  _NOTIFICATION._serialized_start=79
  _NOTIFICATION._serialized_end=141
# @@protoc_insertion_point(module_scope)
